# Copyright 2025 The ElementOS Project
# SPDX-License-Identifier: Apache-2.0

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_VARIANT := exynos
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_SMP := true

# Kernel
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_SOURCE := kernel/samsung/exynos990
TARGET_KERNEL_CONFIG := element_r8s_defconfig
TARGET_KERNEL_CLANG_COMPILE := true
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-gnu-
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb

# DTB
TARGET_KERNEL_DTB := exynos990-r8s
BOARD_KERNEL_DTB := exynos990-r8s.dtb

# Boot parameters (from stock boot.img cmdline)
BOARD_KERNEL_CMDLINE := console=null androidboot.hardware=exynos990 androidboot.selinux=permissive
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x02000000
BOARD_TAGS_OFFSET := 0x01e00000
BOARD_DTB_OFFSET := 0x01f00000

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 83886080
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_SUPER_PARTITION_SIZE := 8925478912

# Filesystem
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
BOARD_SYSTEM_IMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Android Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 2

# Recovery
TARGET_RECOVERY_FSTAB := device/samsung/r8s/recovery.fstab
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_RECOVERY_KERNEL_MODULES := true

# Security
BOARD_BOOT_HEADER_VERSION := 2
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
